'''<br><br>
    @Author: Ayush Prajapati <br>
    @Date: 06-07-2024 <br>
    @Last Modified by: Ayush Prajapati <br>
    @Last Modified time: 07-07-2024 <br>
    @Title: Python Programs on Numpy Library
<br><br>
'''

In [3]:
import numpy as np

## Q1
Python program to convert a list of numeric value into a one-dimensional NumPy array

In [3]:
def main():
    n = int(input("Enter number of element in the list: "))
    num_list = []
    for index in range(n):
        num_list.append(float(input(f"Enter {index+1} element: ")))

    print(f"The orignal list is: {num_list}")
    arr = np.array(num_list)
    print(f"The converted {arr} is of type {type(arr)} ")

In [4]:
if __name__ == "__main__":
    main()

The orignal list is: [1.0, 2.0, 3.0, 4.0, 5.0]
The converted [1. 2. 3. 4. 5.] is of type <class 'numpy.ndarray'> 


## Q2
Python program to create a 3x3 matrix with values ranging from 2 to 10.

In [5]:
def main():
    arr = np.array([x for x in range(2, 11)])
    print(arr.reshape(3,3))

In [6]:
if __name__ == "__main__":
    main()

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


## Q3
Python program to create a null vector of size 10 and update sixth value to 11.

In [4]:
def main():
    arr = np.array([0 for _ in range(10)], dtype = 'float')
    print(f"The orignal array is {arr}")
    arr[5] = 11
    print(f"The updated array is {arr}")

In [5]:
if __name__ == "__main__":
    main()

The orignal array is [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
The updated array is [ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.]


## Q4
Python program to reverse an array

In [6]:
def reverse_array(arr):
    """
    Description:
        This function reverses the array
    Parameters:
        arr: Num array
    Return:
        arr: Rreversed Array
    """
    start = 0
    temp = 0
    end = len(arr) - 1
    while start < end:
        temp = arr[start]
        arr[start] = arr[end]
        arr[end] = temp

        start += 1
        end -= 1

    return arr

In [7]:
def main():
    n = int(input("Enter number of elements in the array: "))
    num_list = []
    for index in range(n):
        num_list.append(int(input(f"Enter {index+1} element: ")))
        
    arr = np.array(num_list)
    print(f"\nThe orignal array is {arr}")
    print(f"\nThe reversed array is {reverse_array(arr)}")

In [8]:
if __name__ == "__main__":
    main()


The orignal array is [1 2 3 4 5]

The reversed array is [5 4 3 2 1]


## Q5
Python program to create a 2d array with 1 on the border and 0 inside.

In [9]:
def print_pattern(arr):
    """
    Description: 
        This function creates an array with 1 on the border and 0 inside. 
    Parameters:
        arr: orignal array
    Return:
        arr
    """
    for row in range(len(arr)):
        for column in range(len(arr[0])):
            if row == 0 or column == 0 or row == (len(arr) - 1) or column == (len(arr[0]) - 1):
                pass
            else:
                arr[row, column] = 0
    return arr

In [10]:
def main():
    arr = np.array([1 for _ in range(25)])
    arr = arr.reshape(5,5)
    print(f"The orignal array is \n{arr}")
    print(f"\nThe updated array is \n{print_pattern(arr)}")

In [11]:
if __name__ == "__main__":
    main()

The orignal array is 
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]

The updated array is 
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


## Q6
Python program to add a border (filled with 0's) around an existing array.

In [13]:
def add_border(arr):
    """
    Description: 
        This function used to add border(0's) to an existing array
    Parameters:
        arr: array to be updated
    Return:
        arr
    """
    rows, cols = arr.shape
    bordered_array = np.zeros((rows + 2, cols + 2))
    bordered_array[1:-1, 1:-1] = arr
    return bordered_array

In [14]:
def main():
    arr = np.array([1 for _ in range(9)])
    arr = arr.reshape(3,3)
    print(f"The orignal array is \n{arr}")
    print(f"\nThe updated array is \n{add_border(arr)}")

In [15]:
if __name__ == "__main__":
    main()

The orignal array is 
[[1 1 1]
 [1 1 1]
 [1 1 1]]

The updated array is 
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


## Q7
Python program to create a 8x8 matrix and fill it with a checkerboard pattern.

In [16]:
def main():
    checkerboard = np.array([[(i + j) % 2 for j in range(8)] for i in range(8)])
    print(f"The checkerboard array is \n{checkerboard}")

In [17]:
if __name__ == "__main__":
    main()

The checkerboard array is 
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Q8
Python program to convert a list and tuple into arrays.

In [18]:
def main():
    num_list = [1, 2, 3, 4, 5, 6, 7, 8]
    num_tuple = (1, 2, 3, 4, 5, 6, 7, 8)
    lst_to_arr = np.array(num_list)
    lst_to_tuple = np.array(num_tuple).reshape(2,4)
    print(f"The converted array from list is {lst_to_arr} and from tupple is, \n{lst_to_tuple}")

In [19]:
if __name__ == "__main__":
    main()

The converted array from list is [1 2 3 4 5 6 7 8] and from tupple is, 
[[1 2 3 4]
 [5 6 7 8]]


## Q9
Python program to append values to the end of an array.

In [20]:
def main():
    n = int(input("Enter number of elements in the orignal array"))
    arr = np.array([(int(input(f"Enter {i+1} element: "))) for i in range(n)])
    print(f"The orignal array is {arr}")
    n = int(input("\nEnter number of elements to append: "))
    values_to_append = [(int(input(f"Enter {i+1} element: "))) for i in range(n)]
    arr = np.append(arr, values_to_append)
    print(f"The updated array is {arr}")

In [21]:
if __name__ == "__main__":
    main()

The orignal array is [1 2 3 4]
The updated array is [ 1  2  3  4 78 21]


## Q10
Python program to find the real and imaginary parts of an array of complex numbers.

In [22]:
def main():
    complex_nums = np.array([1 + 2j, 3 + 1j])
    print(f"The array {complex_nums} is of type {complex_nums.dtype}")
    print(f"The real part is {complex_nums.real} and imaginary part is {complex_nums.imag}")

In [23]:
if __name__ == "__main__":
    main()

The array [1.+2.j 3.+1.j] is of type complex128
The real part is [1. 3.] and imaginary part is [2. 1.]


## Q11
Python program to find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements.

In [24]:
def main():
    arr = np.array([[1, 2, 3], [1, 2, 3]], dtype = 'int32')
    size_of_array = arr.size
    size_of_element = arr.itemsize
    
    total_bytes = size_of_array * size_of_element
    print(f"Size of the array: {size_of_array}")
    print(f"Length of one array element in bytes: {size_of_element}")
    print(f"Total bytes consumed by the elements of the array: {total_bytes}")

In [25]:
if __name__ == "__main__":
    main()

Size of the array: 6
Length of one array element in bytes: 4
Total bytes consumed by the elements of the array: 24
