'''<br><br>
    @Author: Ayush Prajapati <br>
    @Date: 06-07-2024 <br>
    @Last Modified by: Ayush Prajapati <br>
    @Last Modified time: 07-07-2024 <br>
    @Title: Python Programs on Numpy Library
<br><br>
'''

In [3]:
import numpy as np

## Q1
Python program to convert a list of numeric value into a one-dimensional NumPy array

In [3]:
def main():
    n = int(input("Enter number of element in the list: "))
    num_list = []
    for index in range(n):
        num_list.append(float(input(f"Enter {index+1} element: ")))

    print(f"The orignal list is: {num_list}")
    arr = np.array(num_list)
    print(f"The converted {arr} is of type {type(arr)} ")

In [4]:
if __name__ == "__main__":
    main()

The orignal list is: [1.0, 2.0, 3.0, 4.0, 5.0]
The converted [1. 2. 3. 4. 5.] is of type <class 'numpy.ndarray'> 


## Q2
Python program to create a 3x3 matrix with values ranging from 2 to 10.

In [5]:
def main():
    arr = np.array([x for x in range(2, 11)])
    print(arr.reshape(3,3))

In [6]:
if __name__ == "__main__":
    main()

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


## Q3
Python program to create a null vector of size 10 and update sixth value to 11.

In [4]:
def main():
    arr = np.array([0 for _ in range(10)], dtype = 'float')
    print(f"The orignal array is {arr}")
    arr[5] = 11
    print(f"The updated array is {arr}")

In [5]:
if __name__ == "__main__":
    main()

The orignal array is [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
The updated array is [ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.]


## Q4
Python program to reverse an array

In [6]:
def reverse_array(arr):
    """
    Description:
        This function reverses the array
    Parameters:
        arr: Num array
    Return:
        arr: Rreversed Array
    """
    start = 0
    temp = 0
    end = len(arr) - 1
    while start < end:
        temp = arr[start]
        arr[start] = arr[end]
        arr[end] = temp

        start += 1
        end -= 1

    return arr

In [7]:
def main():
    n = int(input("Enter number of elements in the array: "))
    num_list = []
    for index in range(n):
        num_list.append(int(input(f"Enter {index+1} element: ")))
        
    arr = np.array(num_list)
    print(f"\nThe orignal array is {arr}")
    print(f"\nThe reversed array is {reverse_array(arr)}")

In [8]:
if __name__ == "__main__":
    main()


The orignal array is [1 2 3 4 5]

The reversed array is [5 4 3 2 1]


## Q5
Python program to create a 2d array with 1 on the border and 0 inside.

In [9]:
def print_pattern(arr):
    """
    Description: 
        This function creates an array with 1 on the border and 0 inside. 
    Parameters:
        arr: orignal array
    Return:
        arr
    """
    for row in range(len(arr)):
        for column in range(len(arr[0])):
            if row == 0 or column == 0 or row == (len(arr) - 1) or column == (len(arr[0]) - 1):
                pass
            else:
                arr[row, column] = 0
    return arr

In [10]:
def main():
    arr = np.array([1 for _ in range(25)])
    arr = arr.reshape(5,5)
    print(f"The orignal array is \n{arr}")
    print(f"\nThe updated array is \n{print_pattern(arr)}")

In [11]:
if __name__ == "__main__":
    main()

The orignal array is 
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]

The updated array is 
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


## Q6
Python program to add a border (filled with 0's) around an existing array.

In [13]:
def add_border(arr):
    """
    Description: 
        This function used to add border(0's) to an existing array
    Parameters:
        arr: array to be updated
    Return:
        arr
    """
    rows, cols = arr.shape
    bordered_array = np.zeros((rows + 2, cols + 2))
    bordered_array[1:-1, 1:-1] = arr
    return bordered_array

In [14]:
def main():
    arr = np.array([1 for _ in range(9)])
    arr = arr.reshape(3,3)
    print(f"The orignal array is \n{arr}")
    print(f"\nThe updated array is \n{add_border(arr)}")

In [15]:
if __name__ == "__main__":
    main()

The orignal array is 
[[1 1 1]
 [1 1 1]
 [1 1 1]]

The updated array is 
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


## Q7
Python program to create a 8x8 matrix and fill it with a checkerboard pattern.

In [16]:
def main():
    checkerboard = np.array([[(i + j) % 2 for j in range(8)] for i in range(8)])
    print(f"The checkerboard array is \n{checkerboard}")

In [17]:
if __name__ == "__main__":
    main()

The checkerboard array is 
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Q8
Python program to convert a list and tuple into arrays.

In [18]:
def main():
    num_list = [1, 2, 3, 4, 5, 6, 7, 8]
    num_tuple = (1, 2, 3, 4, 5, 6, 7, 8)
    lst_to_arr = np.array(num_list)
    lst_to_tuple = np.array(num_tuple).reshape(2,4)
    print(f"The converted array from list is {lst_to_arr} and from tupple is, \n{lst_to_tuple}")

In [19]:
if __name__ == "__main__":
    main()

The converted array from list is [1 2 3 4 5 6 7 8] and from tupple is, 
[[1 2 3 4]
 [5 6 7 8]]


## Q9
Python program to append values to the end of an array.

In [20]:
def main():
    n = int(input("Enter number of elements in the orignal array"))
    arr = np.array([(int(input(f"Enter {i+1} element: "))) for i in range(n)])
    print(f"The orignal array is {arr}")
    n = int(input("\nEnter number of elements to append: "))
    values_to_append = [(int(input(f"Enter {i+1} element: "))) for i in range(n)]
    arr = np.append(arr, values_to_append)
    print(f"The updated array is {arr}")

In [21]:
if __name__ == "__main__":
    main()

The orignal array is [1 2 3 4]
The updated array is [ 1  2  3  4 78 21]


## Q10
Python program to find the real and imaginary parts of an array of complex numbers.

In [22]:
def main():
    complex_nums = np.array([1 + 2j, 3 + 1j])
    print(f"The array {complex_nums} is of type {complex_nums.dtype}")
    print(f"The real part is {complex_nums.real} and imaginary part is {complex_nums.imag}")

In [23]:
if __name__ == "__main__":
    main()

The array [1.+2.j 3.+1.j] is of type complex128
The real part is [1. 3.] and imaginary part is [2. 1.]


## Q11
Python program to find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements.

In [24]:
def main():
    arr = np.array([[1, 2, 3], [1, 2, 3]], dtype = 'int32')
    size_of_array = arr.size
    size_of_element = arr.itemsize
    
    total_bytes = size_of_array * size_of_element
    print(f"Size of the array: {size_of_array}")
    print(f"Length of one array element in bytes: {size_of_element}")
    print(f"Total bytes consumed by the elements of the array: {total_bytes}")

In [25]:
if __name__ == "__main__":
    main()

Size of the array: 6
Length of one array element in bytes: 4
Total bytes consumed by the elements of the array: 24


## Q12
Python program to find common values between two arrays.

In [26]:
def common_element_array(arr1, arr2):
    """
    Description: 
        This function used find common elements in two arrays
    Parameters:
        arr1, arr2: 
    Return:
        list: common element list
    """
    common_element = []
    for element in arr1:
        if element in arr2:
            common_element.append(element)
 
    return common_element

In [27]:
def main():
    n = int(input("Enter number of elements in the first array: "))
    arr1 = np.array([(int(input(f"Enter {i+1} element: "))) for i in range(n)])
    print(f"The first array is {arr1}")
    
    n = int(input("\nEnter number of elements in the second array: "))
    arr2 = [(int(input(f"Enter {i+1} element: "))) for i in range(n)]
    print(f"The second array is {arr2}")
    lst = common_element_array(arr1, arr2)
    print(f"\nThe common elements are {common_element_array(arr1, arr2)}")

In [28]:
if __name__ == "__main__":
    main()

The first array is [1 2 3 4 5]
The second array is [1, 2, 7]

The common elements are [1, 2]


## Q13
Python program to find the set difference of two arrays.

In [29]:
def set_difference_array(arr1, arr2):
    """
    Description: 
        This function used find set difference
    Parameters:
        arr1, arr2: 
    Return:
        list: set difference
    """
    set_diff = []
    for element in arr1:
        if element not in arr2:
            set_diff.append(element)
 
    return set_diff

In [32]:
def main():
    n = int(input("Enter number of elements in the first array: "))
    arr1 = np.array([(int(input(f"Enter {i+1} element: "))) for i in range(n)])
    print(f"The first array is {arr1}")
    
    n = int(input("\nEnter number of elements in the second array: "))
    arr2 = [(int(input(f"Enter {i+1} element: "))) for i in range(n)]
    print(f"The second array is {arr2}")
    lst = common_element_array(arr1, arr2)
    print(f"\nThe set difference is: {set_difference_array(arr1, arr2)}")

In [33]:
if __name__ == "__main__":
    main()

The first array is [ 0 10 20 40 60 80]
The second array is [10, 30, 40, 50, 70, 90]

The set difference is: [0, 20, 60, 80]


## Q14
Python program to find the set exclusive-or of two arrays.

In [37]:
def main():
    n = int(input("Enter number of elements in the first array: "))
    arr1 = np.array([(int(input(f"Enter {i+1} element: "))) for i in range(n)])
    print(f"The first array is {arr1}")
    
    n = int(input("\nEnter number of elements in the second array: "))
    arr2 = np.array([(int(input(f"Enter {i+1} element: "))) for i in range(n)])
    print(f"The second array is {arr2}")

    print(f"\nThe set exclusive-or of two arrays is {np.setxor1d(arr1, arr2)}")

In [39]:
if __name__ == "__main__":
    main()

The first array is [ 0 10 20 40 60 80]
The second array is [10 20 30 50 50 70]

The set exclusive-or of two arrays is [ 0 30 40 50 60 70 80]


## Q15
Python program compare two arrays using numpy.

In [42]:
def main():
    n = int(input("Enter number of elements in the first array: "))
    arr1 = np.array([(int(input(f"Enter {i+1} element: "))) for i in range(n)])
    print(f"The first array is {arr1}")
    
    n = int(input("\nEnter number of elements in the second array: "))
    arr2 = np.array([(int(input(f"Enter {i+1} element: "))) for i in range(n)])
    print(f"The second array is {arr2}")

    print(f"\narr1 > arr2 : {arr1 > arr2}")
    print(f"arr1 >= arr2 : {arr1 >= arr2}")
    print(f"arr1 < arr2 : {arr1 < arr2}")
    print(f"arr1 <= arr2 : {arr1 <= arr2}")

In [43]:
if __name__ == "__main__":
    main()

The first array is [1 2]
The second array is [4 5]

arr1 > arr2 : [False False]
arr1 >= arr2 : [False False]
arr1 < arr2 : [ True  True]
arr1 <= arr2 : [ True  True]


## Q16
Python program to save a NumPy array to a text file.

In [44]:
def main():
    n = int(input("Enter number of elements in the array: "))
    arr = np.array([(int(input(f"Enter {i+1} element: "))) for i in range(n)])
    print(f"The array is {arr}")
    print("Saving array in a text file.....")
    np.savetxt("my_array.txt", arr)
    print("Save Sucessful")

In [45]:
if __name__ == "__main__":
    main()

The array is [1 2 3 4 5]
Saving array in a text file.....
Save Sucessful


## Q17
Python program to create a contiguous flattened array.

In [46]:
def main():
    arr = np.array([[1, 5, 6, 7], [8, 9, 12,18]]) 
    print("Original array:\n", arr) 
    
    flattened_array = np.ravel(arr) 
    print("\nNew flattened array:\n", flattened_array) 

In [47]:
if __name__ == "__main__":
    main()

Original array:
 [[ 1  5  6  7]
 [ 8  9 12 18]]

New flattened array:
 [ 1  5  6  7  8  9 12 18]


## Q18
Python program to change the data type of an array.

In [48]:
def main():
    n = int(input("Enter number of elements in the array: "))
    arr = np.array([(float(input(f"Enter {i+1} element: "))) for i in range(n)])
    print(f"The array is {arr}")
    print(f"\nThe orignal datatype of array is {arr.dtype}")
    
    new_arr = arr.astype(int)
    print(f"\nThe converted array is {new_arr}")
    print(f"The coverted datatype of array is {new_arr.dtype}")

In [50]:
if __name__ == "__main__":
    main()

The array is [1.23 2.43 0.9  9.24]

The orignal datatype of array is float64

The converted array is [1 2 0 9]
The coverted datatype of array is int64


## Q19
Python program to create a 3x3 array with ones on a diagonal and zeros elsewhere

In [54]:
def main():
    identity_arr = np.identity(3)
    print(identity_arr)


if __name__ == "__main__":
    main()

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Q20
Python program to create an array which looks like below array.<br>
Expected Output:<br>
[[ 0. 0. 0.]<br>
[ 1. 0. 0.]<br>
[ 1. 1. 0.]]

In [55]:
def main():
    arr = np.zeros((4,3))

    for row in range(len(arr)):
        for column in range(row):
            arr[row, column] = 1

    print(arr)


if __name__ == "__main__":
    main()

[[0. 0. 0.]
 [1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]


## Q21
Python program to concatenate two 2-dimensional arrays.

In [57]:
def concatenate_arrays(arr1, arr2):
  """
  Desciption:
    Concatenates two 2D arrays horizontally.
  Parameter:
    arr1: The first 2D array.
    arr2: The second 2D array.
  Returns:
    The concatenated 2D array.
  """
  return np.concatenate((arr1, arr2), axis=1)

In [58]:
def main():
    arr1 = [[0, 1, 3], [5, 7, 9]]
    arr2 = [[0, 2, 4], [6, 8, 10]]
    
    result = concatenate_arrays(arr1, arr2)
    print(result)


if __name__ == "__main__":
    main()

[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]


## Q22
Python program to make an array immutable (read-only).

In [59]:
def main():
    nums = np.arange(10)
    print(f"The array is {nums}")
    nums.flags.writeable = False
    nums[0] = 1
    

if __name__ == "__main__":
    main()

The array is [0 1 2 3 4 5 6 7 8 9]


ValueError: assignment destination is read-only

## Q23
Python program to create an array of (3, 4) shape, multiply every element value by 3 and display the new array.

In [60]:
def main():
    # arr = np.ones((3,4))
    arr = np.array([[0, 1, 2, 3],
            [4, 5, 6, 7],
            [8, 9, 10, 11]])
    print(f"The orignal array is:\n{arr}")
    n = int(input("\nEnter the number to be multiplied by array: "))
    arr = arr * n
    print(f"\nThe multiplied array is:\n{arr}")


if __name__ == "__main__":
    main()

The orignal array is:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

The multiplied array is:
[[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]


## Q24
Python program to convert a NumPy array into Python list structure.

In [61]:
def main():
    # n = int(input("Enter number of elements in the array: "))
    # arr = np.array([(int(input(f"Enter {i+1} element: "))) for i in range(n)])
    arr = np.array([[0, 1],[2, 3], [4, 5]])
    print(f"The array is \n{arr}")

    print(f"\nThe numpy array converted into list is {arr.tolist()}")
    # print(f"\nThe numpy array converted into list is: \n{list(arr)}")


if __name__ == "__main__":
    main()

The array is 
[[0 1]
 [2 3]
 [4 5]]

The numpy array converted into list is [[0, 1], [2, 3], [4, 5]]


## Q25
Python program to print array values with precision 3.

In [62]:
def main():
    arr = np.array([0.26153123, 0.52760141, 0.5718299, 0.5927067, 0.7831874, 0.69746349, 0.35399976, 0.99469633, 0.0694458, 0.54711478])
    print(f"The array is:\n{arr}")

    np.set_printoptions(precision=3)
    print(f"\nThe array values with precision 3 is:\n{arr}")


if __name__ == "__main__":
    main()

The array is:
[0.26153123 0.52760141 0.5718299  0.5927067  0.7831874  0.69746349
 0.35399976 0.99469633 0.0694458  0.54711478]

The array values with precision 3 is:
[0.262 0.528 0.572 0.593 0.783 0.697 0.354 0.995 0.069 0.547]


## Q26
Python program to suppresses the use of scientific notation for small numbers in numpy array.

In [63]:
def main():
    arr = np.array([1.60000000e-10, 1.60000000e+00, 1.20000000e+03, 2.35000000e-01])
    print(f"The array is:\n{arr}")

    np.set_printoptions(precision = 3, suppress = True)
    print(f"\nThe array values with precision 3 is:\n{arr}")


if __name__ == "__main__":
    main()

The array is:
[1.60e-10 1.60e+00 1.20e+03 2.35e-01]

The array values with precision 3 is:
[   0.       1.6   1200.       0.235]
