'''<br><br>
    @Author: Ayush Prajapati <br>
    @Date: 06-07-2024 <br>
    @Last Modified by: Ayush Prajapati <br>
    @Last Modified time: 07-07-2024 <br>
    @Title: Python Programs on Numpy Library
<br><br>
'''

In [3]:
import numpy as np

## Q1
Python program to convert a list of numeric value into a one-dimensional NumPy array

In [3]:
def main():
    n = int(input("Enter number of element in the list: "))
    num_list = []
    for index in range(n):
        num_list.append(float(input(f"Enter {index+1} element: ")))

    print(f"The orignal list is: {num_list}")
    arr = np.array(num_list)
    print(f"The converted {arr} is of type {type(arr)} ")

In [4]:
if __name__ == "__main__":
    main()

The orignal list is: [1.0, 2.0, 3.0, 4.0, 5.0]
The converted [1. 2. 3. 4. 5.] is of type <class 'numpy.ndarray'> 


## Q2
Python program to create a 3x3 matrix with values ranging from 2 to 10.

In [5]:
def main():
    arr = np.array([x for x in range(2, 11)])
    print(arr.reshape(3,3))

In [6]:
if __name__ == "__main__":
    main()

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


## Q3
Python program to create a null vector of size 10 and update sixth value to 11.

In [4]:
def main():
    arr = np.array([0 for _ in range(10)], dtype = 'float')
    print(f"The orignal array is {arr}")
    arr[5] = 11
    print(f"The updated array is {arr}")

In [5]:
if __name__ == "__main__":
    main()

The orignal array is [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
The updated array is [ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.]


## Q4
Python program to reverse an array

In [6]:
def reverse_array(arr):
    """
    Description:
        This function reverses the array
    Parameters:
        arr: Num array
    Return:
        arr: Rreversed Array
    """
    start = 0
    temp = 0
    end = len(arr) - 1
    while start < end:
        temp = arr[start]
        arr[start] = arr[end]
        arr[end] = temp

        start += 1
        end -= 1

    return arr

In [7]:
def main():
    n = int(input("Enter number of elements in the array: "))
    num_list = []
    for index in range(n):
        num_list.append(int(input(f"Enter {index+1} element: ")))
        
    arr = np.array(num_list)
    print(f"\nThe orignal array is {arr}")
    print(f"\nThe reversed array is {reverse_array(arr)}")

In [8]:
if __name__ == "__main__":
    main()


The orignal array is [1 2 3 4 5]

The reversed array is [5 4 3 2 1]
